spring:
  application:
    name: buku-service

server:
  port: 8085  # port untuk anggota-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # alamat eureka server
    register-with-eureka: true
    fetch-registry: true
