## YAML Template.
---
server:
    port: 9001
    
spring:
    application:
        name: API-GATEWAY1
    cloud:
        gateway:
                mvc:
                    routes:
                        - id: anggota
                          uri: lb://anggota-service
                          predicates: 
                            - Path=/api/anggota/**
                        - id: buku
                          uri: lb://buku-service
                          predicates: 
                            - Path=/api/buku/**
                        - id: peminjaman
                          uri: lb://peminjaman-service
                          predicates: 
                            - Path=/api/peminjaman/**
                        - id: pengembalian
                          uri: lb://pengembalian-service
                          predicates: 
                            - Path=/api/pengembalian/**
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost